// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/wasmforge/internal/proxy (interfaces: Builder)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/proxy/builder.go -package=proxy . Builder
//

// Package proxy is a generated GoMock package.
package proxy

import (
	http "net/http"
	reflect "reflect"

	proxy "github.com/mikhail5545/wasmforge/internal/proxy"
	gomock "go.uber.org/mock/gomock"
)

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
	isgomock struct{}
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &MockBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	return m.recorder
}

// BuildRoute mocks base method.
func (m *MockBuilder) BuildRoute(targetURL, path string, allowedMethods []string, transportCfg proxy.TransportConfig, middlewares ...func(http.Handler) http.Handler) error {
	m.ctrl.T.Helper()
	varargs := []any{targetURL, path, allowedMethods, transportCfg}
	for _, a := range middlewares {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BuildRoute", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildRoute indicates an expected call of BuildRoute.
func (mr *MockBuilderMockRecorder) BuildRoute(targetURL, path, allowedMethods, transportCfg any, middlewares ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{targetURL, path, allowedMethods, transportCfg}, middlewares...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildRoute", reflect.TypeOf((*MockBuilder)(nil).BuildRoute), varargs...)
}

// Director mocks base method.
func (m *MockBuilder) Director() *proxy.Director {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Director")
	ret0, _ := ret[0].(*proxy.Director)
	return ret0
}

// Director indicates an expected call of Director.
func (mr *MockBuilderMockRecorder) Director() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Director", reflect.TypeOf((*MockBuilder)(nil).Director))
}

// RebuildRouteMiddlewares mocks base method.
func (m *MockBuilder) RebuildRouteMiddlewares(path string, middlewares ...func(http.Handler) http.Handler) error {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range middlewares {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RebuildRouteMiddlewares", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildRouteMiddlewares indicates an expected call of RebuildRouteMiddlewares.
func (mr *MockBuilderMockRecorder) RebuildRouteMiddlewares(path any, middlewares ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, middlewares...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildRouteMiddlewares", reflect.TypeOf((*MockBuilder)(nil).RebuildRouteMiddlewares), varargs...)
}

// RemoveRoute mocks base method.
func (m *MockBuilder) RemoveRoute(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoute", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoute indicates an expected call of RemoveRoute.
func (mr *MockBuilderMockRecorder) RemoveRoute(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoute", reflect.TypeOf((*MockBuilder)(nil).RemoveRoute), path)
}
