// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/wasmforge/internal/proxy (interfaces: Factory)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/proxy/factory.go -package=proxy . Factory
//

// Package proxy is a generated GoMock package.
package proxy

import (
	context "context"
	reflect "reflect"

	route "github.com/mikhail5545/wasmforge/internal/models/route"
	plugins "github.com/mikhail5545/wasmforge/internal/models/route/plugins"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// Assemble mocks base method.
func (m *MockFactory) Assemble(ctx context.Context, arg1 *route.Route, arg2 []*plugins.RoutePlugin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assemble", ctx, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assemble indicates an expected call of Assemble.
func (mr *MockFactoryMockRecorder) Assemble(ctx, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assemble", reflect.TypeOf((*MockFactory)(nil).Assemble), ctx, arg1, arg2)
}

// Disassemble mocks base method.
func (m *MockFactory) Disassemble(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disassemble", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disassemble indicates an expected call of Disassemble.
func (mr *MockFactoryMockRecorder) Disassemble(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disassemble", reflect.TypeOf((*MockFactory)(nil).Disassemble), path)
}

// Reassemble mocks base method.
func (m *MockFactory) Reassemble(ctx context.Context, arg1 *route.Route, arg2 []*plugins.RoutePlugin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reassemble", ctx, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reassemble indicates an expected call of Reassemble.
func (mr *MockFactoryMockRecorder) Reassemble(ctx, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reassemble", reflect.TypeOf((*MockFactory)(nil).Reassemble), ctx, arg1, arg2)
}
