// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/wasmforge/internal/proxy (interfaces: RequestObserver,PluginRequestObserver)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/proxy/observer.go -package=proxy . RequestObserver,PluginRequestObserver
//

// Package proxy is a generated GoMock package.
package proxy

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRequestObserver is a mock of RequestObserver interface.
type MockRequestObserver struct {
	ctrl     *gomock.Controller
	recorder *MockRequestObserverMockRecorder
	isgomock struct{}
}

// MockRequestObserverMockRecorder is the mock recorder for MockRequestObserver.
type MockRequestObserverMockRecorder struct {
	mock *MockRequestObserver
}

// NewMockRequestObserver creates a new mock instance.
func NewMockRequestObserver(ctrl *gomock.Controller) *MockRequestObserver {
	mock := &MockRequestObserver{ctrl: ctrl}
	mock.recorder = &MockRequestObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestObserver) EXPECT() *MockRequestObserverMockRecorder {
	return m.recorder
}

// OverallMiddleware mocks base method.
func (m *MockRequestObserver) OverallMiddleware() func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OverallMiddleware")
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// OverallMiddleware indicates an expected call of OverallMiddleware.
func (mr *MockRequestObserverMockRecorder) OverallMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OverallMiddleware", reflect.TypeOf((*MockRequestObserver)(nil).OverallMiddleware))
}

// RouteMiddleware mocks base method.
func (m *MockRequestObserver) RouteMiddleware(routePath string) func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteMiddleware", routePath)
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// RouteMiddleware indicates an expected call of RouteMiddleware.
func (mr *MockRequestObserverMockRecorder) RouteMiddleware(routePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteMiddleware", reflect.TypeOf((*MockRequestObserver)(nil).RouteMiddleware), routePath)
}

// MockPluginRequestObserver is a mock of PluginRequestObserver interface.
type MockPluginRequestObserver struct {
	ctrl     *gomock.Controller
	recorder *MockPluginRequestObserverMockRecorder
	isgomock struct{}
}

// MockPluginRequestObserverMockRecorder is the mock recorder for MockPluginRequestObserver.
type MockPluginRequestObserverMockRecorder struct {
	mock *MockPluginRequestObserver
}

// NewMockPluginRequestObserver creates a new mock instance.
func NewMockPluginRequestObserver(ctrl *gomock.Controller) *MockPluginRequestObserver {
	mock := &MockPluginRequestObserver{ctrl: ctrl}
	mock.recorder = &MockPluginRequestObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginRequestObserver) EXPECT() *MockPluginRequestObserverMockRecorder {
	return m.recorder
}

// PluginMiddleware mocks base method.
func (m *MockPluginRequestObserver) PluginMiddleware(routePath, routePluginID string) func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PluginMiddleware", routePath, routePluginID)
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// PluginMiddleware indicates an expected call of PluginMiddleware.
func (mr *MockPluginRequestObserverMockRecorder) PluginMiddleware(routePath, routePluginID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PluginMiddleware", reflect.TypeOf((*MockPluginRequestObserver)(nil).PluginMiddleware), routePath, routePluginID)
}
