// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/wasmforge/internal/database/proxy/stats (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/database/proxy/stats/repository.go -package=stats . Repository
//

// Package stats is a generated GoMock package.
package stats

import (
	context "context"
	reflect "reflect"
	time "time"

	stats "github.com/mikhail5545/wasmforge/internal/database/proxy/stats"
	stats0 "github.com/mikhail5545/wasmforge/internal/models/proxy/stats"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DB mocks base method.
func (m *MockRepository) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockRepositoryMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockRepository)(nil).DB))
}

// ListWindow mocks base method.
func (m *MockRepository) ListWindow(ctx context.Context, scope stats0.Scope, routePath *string, from, to time.Time) ([]*stats0.RequestStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWindow", ctx, scope, routePath, from, to)
	ret0, _ := ret[0].([]*stats0.RequestStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWindow indicates an expected call of ListWindow.
func (mr *MockRepositoryMockRecorder) ListWindow(ctx, scope, routePath, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWindow", reflect.TypeOf((*MockRepository)(nil).ListWindow), ctx, scope, routePath, from, to)
}

// PruneOlderThan mocks base method.
func (m *MockRepository) PruneOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneOlderThan", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PruneOlderThan indicates an expected call of PruneOlderThan.
func (mr *MockRepositoryMockRecorder) PruneOlderThan(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneOlderThan", reflect.TypeOf((*MockRepository)(nil).PruneOlderThan), ctx, cutoff)
}

// UpsertBatch mocks base method.
func (m *MockRepository) UpsertBatch(ctx context.Context, rows []*stats0.RequestStat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockRepositoryMockRecorder) UpsertBatch(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockRepository)(nil).UpsertBatch), ctx, rows)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx *gorm.DB) stats.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(stats.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
