// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/wasmforge/internal/services/auth (interfaces: TokenIssuer)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/auth/issuer.go -package=auth . TokenIssuer
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	config "github.com/mikhail5545/wasmforge/internal/models/auth/config"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenIssuer is a mock of TokenIssuer interface.
type MockTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenIssuerMockRecorder
	isgomock struct{}
}

// MockTokenIssuerMockRecorder is the mock recorder for MockTokenIssuer.
type MockTokenIssuerMockRecorder struct {
	mock *MockTokenIssuer
}

// NewMockTokenIssuer creates a new mock instance.
func NewMockTokenIssuer(ctrl *gomock.Controller) *MockTokenIssuer {
	mock := &MockTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenIssuer) EXPECT() *MockTokenIssuerMockRecorder {
	return m.recorder
}

// IssueToken mocks base method.
func (m *MockTokenIssuer) IssueToken(ctx context.Context, claims map[string]any, arg2 *config.AuthConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueToken", ctx, claims, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueToken indicates an expected call of IssueToken.
func (mr *MockTokenIssuerMockRecorder) IssueToken(ctx, claims, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueToken", reflect.TypeOf((*MockTokenIssuer)(nil).IssueToken), ctx, claims, arg2)
}
