// Code generated by MockGen. DO NOT EDIT.

package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	configrepo "github.com/mikhail5545/wasmforge/internal/database/auth/config"
	keyrepo "github.com/mikhail5545/wasmforge/internal/database/auth/key"
	configmodel "github.com/mikhail5545/wasmforge/internal/models/auth/config"
	keymodel "github.com/mikhail5545/wasmforge/internal/models/auth/key"
	gomock "go.uber.org/mock/gomock"
	"gorm.io/gorm"
)

type MockKeyMaterialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKeyMaterialRepositoryMockRecorder
}

type MockKeyMaterialRepositoryMockRecorder struct {
	mock *MockKeyMaterialRepository
}

func NewMockKeyMaterialRepository(ctrl *gomock.Controller) *MockKeyMaterialRepository {
	mock := &MockKeyMaterialRepository{ctrl: ctrl}
	mock.recorder = &MockKeyMaterialRepositoryMockRecorder{mock}
	return mock
}

func (m *MockKeyMaterialRepository) EXPECT() *MockKeyMaterialRepositoryMockRecorder {
	return m.recorder
}

func (m *MockKeyMaterialRepository) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

func (mr *MockKeyMaterialRepositoryMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockKeyMaterialRepository)(nil).DB))
}

func (m *MockKeyMaterialRepository) WithTx(tx *gorm.DB) keyrepo.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(keyrepo.Repository)
	return ret0
}

func (mr *MockKeyMaterialRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockKeyMaterialRepository)(nil).WithTx), tx)
}

func (m *MockKeyMaterialRepository) Get(ctx context.Context, opt ...keyrepo.FilterOption) (*keymodel.Material, error) {
	m.ctrl.T.Helper()
	args := []any{ctx}
	for _, option := range opt {
		args = append(args, option)
	}
	ret := m.ctrl.Call(m, "Get", args...)
	ret0, _ := ret[0].(*keymodel.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockKeyMaterialRepositoryMockRecorder) Get(ctx any, opt ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	args := append([]any{ctx}, opt...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKeyMaterialRepository)(nil).Get), args...)
}

func (m *MockKeyMaterialRepository) List(ctx context.Context, opt ...keyrepo.FilterOption) ([]*keymodel.Material, string, error) {
	m.ctrl.T.Helper()
	args := []any{ctx}
	for _, option := range opt {
		args = append(args, option)
	}
	ret := m.ctrl.Call(m, "List", args...)
	ret0, _ := ret[0].([]*keymodel.Material)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockKeyMaterialRepositoryMockRecorder) List(ctx any, opt ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	args := append([]any{ctx}, opt...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockKeyMaterialRepository)(nil).List), args...)
}

func (m *MockKeyMaterialRepository) UnpaginatedList(ctx context.Context, opt ...keyrepo.FilterOption) ([]*keymodel.Material, error) {
	m.ctrl.T.Helper()
	args := []any{ctx}
	for _, option := range opt {
		args = append(args, option)
	}
	ret := m.ctrl.Call(m, "UnpaginatedList", args...)
	ret0, _ := ret[0].([]*keymodel.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockKeyMaterialRepositoryMockRecorder) UnpaginatedList(ctx any, opt ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	args := append([]any{ctx}, opt...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpaginatedList", reflect.TypeOf((*MockKeyMaterialRepository)(nil).UnpaginatedList), args...)
}

func (m *MockKeyMaterialRepository) Create(ctx context.Context, material *keymodel.Material) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, material)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockKeyMaterialRepositoryMockRecorder) Create(ctx, material any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockKeyMaterialRepository)(nil).Create), ctx, material)
}

func (m *MockKeyMaterialRepository) Update(ctx context.Context, material *keymodel.Material) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, material)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockKeyMaterialRepositoryMockRecorder) Update(ctx, material any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockKeyMaterialRepository)(nil).Update), ctx, material)
}

func (m *MockKeyMaterialRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockKeyMaterialRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKeyMaterialRepository)(nil).Delete), ctx, id)
}

func (m *MockKeyMaterialRepository) GetByID(ctx context.Context, id string) (*keymodel.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*keymodel.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockKeyMaterialRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockKeyMaterialRepository)(nil).GetByID), ctx, id)
}

func (m *MockKeyMaterialRepository) GetByKeyID(ctx context.Context, keyID string) (*keymodel.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKeyID", ctx, keyID)
	ret0, _ := ret[0].(*keymodel.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockKeyMaterialRepositoryMockRecorder) GetByKeyID(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKeyID", reflect.TypeOf((*MockKeyMaterialRepository)(nil).GetByKeyID), ctx, keyID)
}

func (m *MockKeyMaterialRepository) ListByAuthConfig(ctx context.Context, authConfigID interface{}) ([]*keymodel.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAuthConfig", ctx, authConfigID)
	ret0, _ := ret[0].([]*keymodel.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockKeyMaterialRepositoryMockRecorder) ListByAuthConfig(ctx, authConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAuthConfig", reflect.TypeOf((*MockKeyMaterialRepository)(nil).ListByAuthConfig), ctx, authConfigID)
}

func (m *MockKeyMaterialRepository) ListActiveByAuthConfig(ctx context.Context, authConfigID interface{}) ([]*keymodel.Material, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByAuthConfig", ctx, authConfigID)
	ret0, _ := ret[0].([]*keymodel.Material)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockKeyMaterialRepositoryMockRecorder) ListActiveByAuthConfig(ctx, authConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByAuthConfig", reflect.TypeOf((*MockKeyMaterialRepository)(nil).ListActiveByAuthConfig), ctx, authConfigID)
}

type MockConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRepositoryMockRecorder
}

type MockConfigRepositoryMockRecorder struct {
	mock *MockConfigRepository
}

func NewMockConfigRepository(ctrl *gomock.Controller) *MockConfigRepository {
	mock := &MockConfigRepository{ctrl: ctrl}
	mock.recorder = &MockConfigRepositoryMockRecorder{mock}
	return mock
}

func (m *MockConfigRepository) EXPECT() *MockConfigRepositoryMockRecorder {
	return m.recorder
}

func (m *MockConfigRepository) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

func (mr *MockConfigRepositoryMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockConfigRepository)(nil).DB))
}

func (m *MockConfigRepository) WithTx(tx *gorm.DB) configrepo.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(configrepo.Repository)
	return ret0
}

func (mr *MockConfigRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockConfigRepository)(nil).WithTx), tx)
}

func (m *MockConfigRepository) Get(ctx context.Context, opt ...configrepo.FilterOption) (*configmodel.AuthConfig, error) {
	m.ctrl.T.Helper()
	args := []any{ctx}
	for _, option := range opt {
		args = append(args, option)
	}
	ret := m.ctrl.Call(m, "Get", args...)
	ret0, _ := ret[0].(*configmodel.AuthConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockConfigRepositoryMockRecorder) Get(ctx any, opt ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	args := append([]any{ctx}, opt...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigRepository)(nil).Get), args...)
}

func (m *MockConfigRepository) List(ctx context.Context, opt ...configrepo.FilterOption) ([]*configmodel.AuthConfig, string, error) {
	m.ctrl.T.Helper()
	args := []any{ctx}
	for _, option := range opt {
		args = append(args, option)
	}
	ret := m.ctrl.Call(m, "List", args...)
	ret0, _ := ret[0].([]*configmodel.AuthConfig)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockConfigRepositoryMockRecorder) List(ctx any, opt ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	args := append([]any{ctx}, opt...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConfigRepository)(nil).List), args...)
}

func (m *MockConfigRepository) UnpaginatedList(ctx context.Context, opt ...configrepo.FilterOption) ([]*configmodel.AuthConfig, error) {
	m.ctrl.T.Helper()
	args := []any{ctx}
	for _, option := range opt {
		args = append(args, option)
	}
	ret := m.ctrl.Call(m, "UnpaginatedList", args...)
	ret0, _ := ret[0].([]*configmodel.AuthConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockConfigRepositoryMockRecorder) UnpaginatedList(ctx any, opt ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	args := append([]any{ctx}, opt...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpaginatedList", reflect.TypeOf((*MockConfigRepository)(nil).UnpaginatedList), args...)
}

func (m *MockConfigRepository) Create(ctx context.Context, cfg *configmodel.AuthConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockConfigRepositoryMockRecorder) Create(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConfigRepository)(nil).Create), ctx, cfg)
}

func (m *MockConfigRepository) Update(ctx context.Context, cfg *configmodel.AuthConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockConfigRepositoryMockRecorder) Update(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConfigRepository)(nil).Update), ctx, cfg)
}

func (m *MockConfigRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockConfigRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConfigRepository)(nil).Delete), ctx, id)
}

func (m *MockConfigRepository) GetByRoute(ctx context.Context, routeID uuid.UUID) (*configmodel.AuthConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoute", ctx, routeID)
	ret0, _ := ret[0].(*configmodel.AuthConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockConfigRepositoryMockRecorder) GetByRoute(ctx, routeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoute", reflect.TypeOf((*MockConfigRepository)(nil).GetByRoute), ctx, routeID)
}
