// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/wasmforge/internal/uploads (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/uploads/manager.go -package=uploads . Manager
//

// Package uploads is a generated GoMock package.
package uploads

import (
	multipart "mime/multipart"
	reflect "reflect"

	uploads "github.com/mikhail5545/wasmforge/internal/uploads"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CertUploadDir mocks base method.
func (m *MockManager) CertUploadDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CertUploadDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// CertUploadDir indicates an expected call of CertUploadDir.
func (mr *MockManagerMockRecorder) CertUploadDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CertUploadDir", reflect.TypeOf((*MockManager)(nil).CertUploadDir))
}

// Delete mocks base method.
func (m *MockManager) Delete(filename string, uploadType uploads.UploadType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", filename, uploadType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManagerMockRecorder) Delete(filename, uploadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManager)(nil).Delete), filename, uploadType)
}

// EnsureDirectory mocks base method.
func (m *MockManager) EnsureDirectory(uploadType uploads.UploadType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDirectory", uploadType)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDirectory indicates an expected call of EnsureDirectory.
func (mr *MockManagerMockRecorder) EnsureDirectory(uploadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDirectory", reflect.TypeOf((*MockManager)(nil).EnsureDirectory), uploadType)
}

// FromBase64 mocks base method.
func (m *MockManager) FromBase64(encodedData, filename string, uploadType uploads.UploadType) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromBase64", encodedData, filename, uploadType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromBase64 indicates an expected call of FromBase64.
func (mr *MockManagerMockRecorder) FromBase64(encodedData, filename, uploadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromBase64", reflect.TypeOf((*MockManager)(nil).FromBase64), encodedData, filename, uploadType)
}

// FromBytes mocks base method.
func (m *MockManager) FromBytes(data []byte, filename string, uploadType uploads.UploadType) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromBytes", data, filename, uploadType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromBytes indicates an expected call of FromBytes.
func (mr *MockManagerMockRecorder) FromBytes(data, filename, uploadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromBytes", reflect.TypeOf((*MockManager)(nil).FromBytes), data, filename, uploadType)
}

// FromMultipartFile mocks base method.
func (m *MockManager) FromMultipartFile(file *multipart.FileHeader, filename string, uploadType uploads.UploadType) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromMultipartFile", file, filename, uploadType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromMultipartFile indicates an expected call of FromMultipartFile.
func (mr *MockManagerMockRecorder) FromMultipartFile(file, filename, uploadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromMultipartFile", reflect.TypeOf((*MockManager)(nil).FromMultipartFile), file, filename, uploadType)
}

// PluginUploadDir mocks base method.
func (m *MockManager) PluginUploadDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PluginUploadDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// PluginUploadDir indicates an expected call of PluginUploadDir.
func (mr *MockManagerMockRecorder) PluginUploadDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PluginUploadDir", reflect.TypeOf((*MockManager)(nil).PluginUploadDir))
}

// Read mocks base method.
func (m *MockManager) Read(filename string, uploadType uploads.UploadType) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", filename, uploadType)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockManagerMockRecorder) Read(filename, uploadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockManager)(nil).Read), filename, uploadType)
}
