// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikhail5545/wasmforge/internal/proxy/middleware (interfaces: Factory)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/proxy/middleware/factory.go -package=middleware . Factory
//

// Package middleware is a generated GoMock package.
package middleware

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFactory) Create(ctx context.Context, wasmBytes []byte, jsonConfig *string) (func(http.Handler) http.Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, wasmBytes, jsonConfig)
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFactoryMockRecorder) Create(ctx, wasmBytes, jsonConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFactory)(nil).Create), ctx, wasmBytes, jsonConfig)
}
